Bootblobs: Move Bootblob templates to shell and allow use in product bundles
Previously the predefined bootblobs were a Makefile facility and only available to source users
With this commit:
- these predefined bootblobs are called bootblob templates
- are implemented in shell fragments
- are copied to the product directory
- are invoked by a new mode of the bootblob script

This allows the creation of bootblobs to be defered until the end user has downloaded a
binary release.  This means she does not need to download a bunch of redundent bits and
(eventually) the created products can be customized by user specific settings.

It is still possible to specify templates that should be run at make product time in setenv.

This commit also quiets the default bootblob operations a bit by default.

Signed-off-by: Bill Mills <wmills@ti.com>

diff --git a/scripts/bootblob b/scripts/bootblob
--- a/scripts/bootblob
+++ b/scripts/bootblob
@@ -1,10 +1,20 @@
 #! /bin/bash
 
+SPEC_DIR=$(cd $(dirname $0); pwd)/bootblob-templates
 PAD_SIZE=0
 ROUND_SIZE=0
 FSIMAGE_START=""
 FSIMAGE_SIZE=""
 ABS_BASE=0
+
+if [ -n "$V" ] && [ "$V" -ne 0 ]; then
+    VERBOSE=true
+    set -x
+else
+    VERBOSE=false
+fi
+
+BEST_EFFORT=false
 
 need-args() {
     found=$1; shift
@@ -80,12 +90,17 @@ my-dd() {
             break;
         fi
     done
-    echo "using blocksize of $BLOCKSIZE"
+    if $VERBOSE; then 
+	echo "using blocksize of $BLOCKSIZE"
+	DD_VERBOSE="/dev/stdout"
+    else
+	DD_VERBOSE="/dev/null"
+    fi
     COUNT=$(($COUNT / $BLOCKSIZE ))
     SEEK=$(($SEEK / $BLOCKSIZE ))
     SKIP=$(($SKIP / $BLOCKSIZE ))
 
-    dd bs=$BLOCKSIZE seek=$SEEK skip=$SKIP count=$COUNT "$@"
+    dd bs=$BLOCKSIZE seek=$SEEK skip=$SKIP count=$COUNT "$@" >$DD_VERBOSE 2>&1
 }
 
 make-image() {
@@ -114,27 +129,79 @@ make-image() {
 
    CMDLINE=$(expand-vars "$CMDLINE")
 
-    printf "kernel   %8.8X  for %10d bytes end at %8.8X\n"  0  $KERNEL_REAL_SIZE $((0+$KERNEL_ROUND_SIZE-1))
-    printf "fsimage  %8.8X  for %10d bytes end at %8.8X\n"  $FSIMAGE_START  $FS_REAL_SIZE  $(($FSIMAGE_START + $FSIMAGE_SIZE-1))
-    printf "total    %8.8X  for %10d bytes end at %8.8X\n"  0 $TOTAL_SIZE $(($TOTAL_SIZE-1))
+    printf "kernel   offset %8.8X  for %10d bytes end at %8.8X\n"  0  $KERNEL_REAL_SIZE $((0+$KERNEL_ROUND_SIZE-1))
+    printf "fsimage  offset %8.8X  for %10d bytes end at %8.8X\n"  $FSIMAGE_START  $FS_REAL_SIZE  $(($FSIMAGE_START + $FSIMAGE_SIZE-1))
+    printf "total    offset %8.8X  for %10d bytes end at %8.8X\n"  0 $TOTAL_SIZE $(($TOTAL_SIZE-1))
     printf "cmdline  %s\n"  "$CMDLINE"
 
-#    dd if=/dev/zero   of=$IMAGE bs=1 count=$TOTAL_SIZE
-#    dd if=$KERNEL     of=$IMAGE conv=notrunc
-#    dd if=$FSIMAGE    of=$IMAGE bs=1 seek=$FSIMAGE_START conv=notrunc
     my-dd $TOTAL_SIZE 0                 0       if=/dev/zero   of=$IMAGE 
     my-dd ""          0                 0       if=$KERNEL     of=$IMAGE conv=notrunc
     my-dd ""          $FSIMAGE_START    0       if=$FSIMAGE    of=$IMAGE conv=notrunc
     set-cmdline $IMAGE "$CMDLINE"
 }
 
+init_rc_check() {
+	ANY_WORKED=false
+	ALL_WORKED=true
+}
+
+one_rc_check() {
+	if "$@" ; then
+		ANY_WORKED=true
+	else
+		ALL_WORKED=false
+	fi
+}
+
+final_rc_check() {
+	if $ANY_WORKED && $ALL_WORKED; then 
+		echo "all specified template combinations suceeded"
+	elif $ANY_WORKED; then
+		echo "some attempted template combinations were skipped"
+	else
+		echo "all attempted template combinations failed"
+	fi
+	
+	if $BEST_EFFORT && $ANY_WORKED ; then
+		return 0
+	elif $ALL_WORKED; then
+		return 0
+	else
+		return 2
+	fi
+}
+
+do_templates() {
+    init_rc_check
+    for template in $@; do
+	if [ -f "$template" ] ; then 
+		TEMPLATE=$(basename $template)
+		source $SPEC_DIR/defs/common.sh
+		source $template
+		do_for_each do_one
+	else
+		one_rc_check false
+	fi
+    done
+    final_rc_check
+}
+
 do_help() {
-    echo "bootblob [options] <cmd> [options] <args>"
+    echo "bootblob [options] <cmd>|<template> [options] <args>"
     echo "where cmd is one of: (run just the command to see the argument description)"
     echo "    make-image              create a new bootblob image"
     echo "    set-cmdline             set command line of a blob image or kernel binary image"
     echo "    get-cmdline             print the current command line of a blob image or kernel binary image"
     echo "    save-cmdline            save the raw cmdline data to a file"
+    echo ""
+    echo "or where template is one of:"
+    for template in $(echo $SPEC_DIR/*); do
+	if [ -f "$template" ] ; then
+		DESC=$(source $template; echo $DESC)
+		printf "    %-38s  $DESC\n" $(basename $template)
+	fi
+    done
+    printf "    %-38s  all the above templates\n" all
     echo ""
     echo "and where options is zero or more of: (use decimal or 0x prefix for hex)"
     echo "    --fsimage-start=        specify the starting offset of the file system image"
@@ -150,9 +217,13 @@ do_help() {
     echo "    %fsimage-size%          size of filesystem image (decimal)"
     echo "    %fsimage-size-x%        size of filesystem image (hex)"
     echo ""
-    echo "example:"
-    echo "    ./bootblob make-image --abs-base=0x80000000 --round=0x100000 test.blob vmlinux-xxx.bin min-root-c6x.cpio.gz \\"
-    echo "        console=cio initrd=0x%fsimage-start-abs-x%,0x%fsimage-size-x% ip=dhcp"
+    echo "example1, make-image:"
+    echo '    ./bootblob make-image --abs-base=0x80000000 --round=0x100000 test.blob vmlinux-xxx.bin min-root-c6x.cpio.gz \'
+    echo '        "console=cio initrd=0x%fsimage-start-abs-x%,0x%fsimage-size-x% ip=dhcp"'
+    echo ""
+    echo "example2, template: "
+    echo '    ./bootblob evm6670-initramfs-min-root'
+    echo ""
 }
 
 handle-one-option() {
@@ -210,6 +281,11 @@ done
 if [ "$1" == "--" ]; then shift; fi
 
 case $CMD in
+    "")
+        echo "must specifiy a command or template, try:"
+        echo "    bootblob help"
+        exit 1
+        ;;
     help)
         do_help
         exit 0
@@ -217,13 +293,16 @@ case $CMD in
     make-image|set-cmdline|get-cmdline|save-cmdline)
         $CMD "$@"
         ;;
-    "")
-        echo "must specifiy a command, try:"
-        echo "    bootblob help"
-        exit 1
-        ;;
+    all)
+	BEST_EFFORT=true
+	do_templates $SPEC_DIR/*
+	;;
     *)
-        echo "unknown command $CMD"
-        exit 1
+	if [ -r "$SPEC_DIR/$CMD" ] ; then
+		do_templates $SPEC_DIR/$CMD
+	else
+		echo "unknown command or template $CMD"
+		exit 1
+	fi
         ;;
 esac
